// /auth/verify — proxy redirect to Supabase's /auth/v1/verify endpoint.
//
// WHY THIS ROUTE EXISTS
// ─────────────────────
// Resend's email-deliverability insights flag any email whose link
// host doesn't match the sending domain as a high spam-risk signal:
//
//   "Ensure link URLs match sending domain. Mismatched URLs can
//    trigger spam filters."
//
// Server-initiated magic links generated by `admin.auth.admin.generateLink`
// return an `action_link` of the form:
//
//   https://<project-ref>.supabase.co/auth/v1/verify?token=<hash>
//                                                  &type=magiclink
//                                                  &redirect_to=https://evenquote.com/...
//
// The link host (`<project>.supabase.co`) does NOT match the sending
// domain (`evenquote.com`) → spam filters (Hotmail/Outlook especially)
// quarantine the email.
//
// Supabase's Custom Domain feature (auth.evenquote.com) fixes this
// natively but requires the Pro plan ($25/mo). On the Free plan, this
// proxy route is the equivalent: callers send the user to
// `https://evenquote.com/auth/verify?...` and we 302-redirect to the
// real Supabase verify endpoint with identical query params. Token
// validation happens on Supabase as before; the user lands on
// `redirect_to` (also evenquote.com) when done. The user-visible link
// in the email matches the sending domain — spam-filter signal goes
// away.
//
// SECURITY NOTES
// ──────────────
//   • This route does NO token validation of its own. The token is
//     opaque to us; Supabase is the validator. We just relay query
//     params.
//   • The token is a one-time-use OTP hash. Visible in our access
//     logs for the brief window before consumption — acceptable since
//     it's single-use and short-lived (default 1 hour).
//   • We hardcode the supabase.co host from NEXT_PUBLIC_SUPABASE_URL
//     so an attacker can't supply a `?supabase_host=evil.com`
//     redirect target.
//
// KNOWN LIMITATION
// ────────────────
// Microsoft Safe Links / link-prefetchers may pre-fetch this URL
// (which then redirects to Supabase, potentially consuming the
// token before the human clicks). If we see real reports of that,
// upgrade this to a static "Click to continue" interstitial page
// that requires user interaction. Not blocking today.

import { NextResponse, type NextRequest } from 'next/server';

const SUPABASE_VERIFY_PATH = '/auth/v1/verify';

export async function GET(request: NextRequest) {
  const url = new URL(request.url);
  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;

  if (!supabaseUrl) {
    // Misconfigured deploy — surface it loudly so ops sees a 500
    // rather than silently breaking auth.
    return new NextResponse('NEXT_PUBLIC_SUPABASE_URL not set', { status: 500 });
  }

  // Build the upstream URL: <supabase-host>/auth/v1/verify + same query string.
  // Reusing url.searchParams preserves token, type, redirect_to, AND any
  // future params Supabase adds without us having to enumerate them.
  const upstream = new URL(SUPABASE_VERIFY_PATH, supabaseUrl);
  upstream.search = url.search;

  // 302 — Supabase's own /auth/v1/verify uses 302 too. Keeps semantics
  // identical to the un-proxied flow.
  return NextResponse.redirect(upstream.toString(), 302);
}
