#!/usr/bin/env -S npx tsx
// Mint N coupon codes via the Supabase Management API.
//
// Usage:
//   SUPABASE_ACCESS_TOKEN=sbp_… \
//     npx tsx scripts/mint-coupons.ts <count> [--max-uses N] [--note "for friends"] [--vertical handyman]
//
// Defaults:
//   count        required
//   --max-uses   1   (single-use)
//   --note       null
//   --vertical   null (any vertical)
//   --expires    null (no expiry)
//
// Output: prints the codes one per line. Hand them to your friends.
//
// Token comes from .env.local (same source as scripts/apply-migration.ts).
// Codes are CSPRNG-generated by lib/coupons/codes.ts.

import { resolve } from 'node:path';
import { config as dotenvConfig } from 'dotenv';
import { generateCouponCode } from '@/lib/coupons/codes';

dotenvConfig({ path: resolve(process.cwd(), '.env.local') });

function die(msg: string): never {
  console.error(`✗ ${msg}`);
  process.exit(1);
}

const PAT = process.env.SUPABASE_ACCESS_TOKEN;
const URL_RAW = process.env.NEXT_PUBLIC_SUPABASE_URL;
if (!PAT) die('SUPABASE_ACCESS_TOKEN env var required.');
if (!URL_RAW) die('NEXT_PUBLIC_SUPABASE_URL not set in .env.local.');
const ref = new URL(URL_RAW).hostname.split('.')[0];
if (!ref || ref.length < 16) die(`Could not derive project ref from URL: ${URL_RAW}`);

// Parse args. Positional: count. Flags: --max-uses N, --note STR,
// --vertical SLUG, --expires ISODATE.
const args = process.argv.slice(2);
const count = Number.parseInt(args[0] ?? '', 10);
if (!Number.isFinite(count) || count < 1 || count > 100) {
  die('First arg must be a count between 1 and 100. Usage: mint-coupons <count> [--max-uses N] [--note "..."] [--vertical slug] [--expires 2026-12-31]');
}

function flag(name: string): string | undefined {
  const i = args.indexOf(`--${name}`);
  if (i === -1) return undefined;
  return args[i + 1];
}

const maxUses = Number.parseInt(flag('max-uses') ?? '1', 10);
if (!Number.isFinite(maxUses) || maxUses < 1) die('--max-uses must be >= 1');
const note = flag('note') ?? null;
const vertical = flag('vertical') ?? null;
const expires = flag('expires') ?? null;
if (expires && Number.isNaN(Date.parse(expires))) {
  die(`--expires must be ISO 8601 (e.g., 2026-12-31 or 2026-12-31T23:59:59Z). Got: ${expires}`);
}

// Generate codes. Loop with collision-detection via a Set; in practice
// 12-char from a 31-alphabet has ~2^59 entropy so collisions in <100
// codes are mathematically negligible, but the dedup is cheap.
const codes = new Set<string>();
while (codes.size < count) codes.add(generateCouponCode());

// Build the bulk INSERT. We use single-row VALUES per code so the
// individual code is visible in the returned response (vs an
// unparseable bulk-insert echo).
const valuesSql = [...codes]
  .map((c) => {
    const cQuoted = `'${c.replace(/'/g, "''")}'`;
    const noteSql = note ? `'${note.replace(/'/g, "''")}'` : 'NULL';
    const verticalSql = vertical ? `'${vertical.replace(/'/g, "''")}'` : 'NULL';
    const expiresSql = expires ? `'${expires}'::timestamptz` : 'NULL';
    return `(${cQuoted}, ${maxUses}, ${expiresSql}, ${verticalSql}, ${noteSql})`;
  })
  .join(',\n  ');

const sql = `
insert into public.coupons (code, max_uses, expires_at, category_slug, notes)
values
  ${valuesSql}
returning code;
`;

console.log(`▸ Project: ${ref}`);
console.log(`▸ Minting: ${count} code(s), max_uses=${maxUses}, vertical=${vertical ?? 'any'}, expires=${expires ?? 'never'}, note=${note ?? '(none)'}`);

async function main(): Promise<void> {
  const res = await fetch(
    `https://api.supabase.com/v1/projects/${ref}/database/query`,
    {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${PAT}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ query: sql }),
    },
  );
  const body = await res.text();
  if (!res.ok) {
    console.error(body);
    die(`HTTP ${res.status}`);
  }
  // Body is JSON: [{ "code": "..." }, ...]
  let parsed: Array<{ code: string }> = [];
  try {
    parsed = JSON.parse(body);
  } catch {
    console.error(body);
    die('Could not parse response.');
  }
  console.log('');
  console.log(`✓ Minted ${parsed.length} coupon(s):`);
  console.log('');
  for (const row of parsed) {
    console.log(`  ${row.code}`);
  }
  console.log('');
  console.log('Customers redeem at https://evenquote.com/get-quotes/<vertical> → checkout → "Have a coupon code?"');
}

main().catch((err) => {
  console.error('✗ Unexpected:', err);
  process.exit(1);
});
