-- ══════════════════════════════════════════════════════════════════════
-- Phase 7.1 — Vapi phone-number pool.
--
-- Replaces the single `VAPI_PHONE_NUMBER_ID` env var with a first-class
-- table of numbers. The outbound call dispatcher (lib/calls/vapi.ts)
-- picks the best number per call via pick_vapi_number() so that:
--
--   1. The outbound caller ID matches the destination's area code when
--      possible ("local presence" — pickup rate lever).
--   2. Calls spread across multiple numbers instead of queuing on one,
--      unlocking real concurrency now that Twilio is on a paid plan.
--   3. Per-number health (status, daily_call_count) is observable and
--      operator-controllable — flip `status = 'flagged'` to pull a
--      number out of rotation without a deploy.
--
-- The selector is intentionally atomic (FOR UPDATE SKIP LOCKED inside
-- an UPDATE ... RETURNING) so two concurrent dispatchers during a burst
-- cannot claim the same number.
--
-- Backward compatibility: if this table is empty, the TypeScript caller
-- falls back to VAPI_PHONE_NUMBER_ID env var. That means this migration
-- can ship before we've populated the pool, and current behaviour is
-- preserved. See docs/RUNBOOKS/add-vapi-number.md for the populate flow.
--
-- Safe to apply: purely additive (one new table, one new function). No
-- changes to existing columns, constraints, or RLS policies elsewhere.
-- ══════════════════════════════════════════════════════════════════════


-- ─── 1. vapi_phone_numbers table ─────────────────────────────────────

create table if not exists public.vapi_phone_numbers (
  -- Vapi's own phoneNumberId (UUID-shaped string). This is what we pass
  -- into the Vapi `/call` body as `phoneNumberId`. Not generated by us
  -- — copied from the Vapi dashboard after registering the Twilio number.
  id                  text primary key,

  -- The underlying Twilio number in E.164 format (+1NXXNXXXXXX). Stored
  -- for human reference and to derive `area_code`. The CHECK enforces
  -- a valid US NANP number (+1 then 10 digits, area code 2-9 prefix).
  -- Non-US numbers are out of scope for v1; add a different column or
  -- relax this constraint when that changes.
  twilio_e164         text not null unique
                      check (twilio_e164 ~ '^\+1[2-9]\d{9}$'),

  -- Derived area code ("415" from "+14155551234"). Generated + STORED
  -- so the selector can index-scan it cheaply. Regenerates automatically
  -- if you ever UPDATE twilio_e164 (which you generally shouldn't).
  area_code           text generated always as (substring(twilio_e164 from 3 for 3)) stored,

  -- US state the number is attached to (two-letter, e.g. "CA"). Optional
  -- for v1 — we only fall back to "any-active" from area-code today —
  -- but populated when available so a future state-level tier can slot
  -- in without a schema change.
  region_state        text,

  -- Rotation control.
  --   active   → eligible for selection
  --   flagged  → carrier complaint / spam score — skip until investigated
  --   retired  → no longer used (kept for audit history)
  status              text not null default 'active'
                      check (status in ('active', 'flagged', 'retired')),

  -- Per-day call counter to respect carrier thresholds. Bumped atomically
  -- inside pick_vapi_number(). Resets opportunistically when daily_reset_at
  -- is older than 24h on the next pick — no cron job needed.
  daily_call_count    int not null default 0,
  daily_reset_at      timestamptz not null default now(),

  -- Last time this number was claimed by pick_vapi_number(). Drives the
  -- round-robin tiebreak ("least recently used wins").
  last_used_at        timestamptz,

  -- Most recent error observed for this number (set by ops or a future
  -- health checker). Human-readable; not machine-consumed.
  last_error          text,

  -- Free-form operator notes ("SD local for moving vertical", etc).
  notes               text,

  created_at          timestamptz not null default now()
);

comment on table public.vapi_phone_numbers is
  'Pool of Vapi phone numbers for outbound calls. Claimed atomically via pick_vapi_number(). See docs/RUNBOOKS/add-vapi-number.md for provisioning.';

-- Partial indexes — both selector tiers scan only active rows.
-- The area-code index covers the primary lookup; the fallback index
-- covers tier-2 ("any active") scans when the area-code pool is empty.
create index if not exists vapi_phone_numbers_area_code_active_idx
  on public.vapi_phone_numbers (area_code, last_used_at nulls first)
  where status = 'active';

create index if not exists vapi_phone_numbers_active_lru_idx
  on public.vapi_phone_numbers (last_used_at nulls first)
  where status = 'active';

-- RLS: no user-facing access. Service role bypasses RLS; anon and
-- authenticated roles get nothing because no policies are defined.
alter table public.vapi_phone_numbers enable row level security;


-- ─── 2. pick_vapi_number() — atomic selector ─────────────────────────
--
-- Two-tier fallback ladder:
--
--   tier 1 ("area_code") — active numbers matching p_area_code, under
--                          the daily cap, least-recently-used wins.
--   tier 2 ("any")       — any active number under the daily cap,
--                          least-recently-used wins.
--
-- Each tier is a single UPDATE ... WHERE id = (SELECT ... FOR UPDATE
-- SKIP LOCKED) RETURNING — which both atomically claims the row (bumps
-- last_used_at + daily_call_count) and tells the caller which number
-- was picked. SKIP LOCKED lets concurrent dispatchers coexist without
-- blocking each other.
--
-- Daily count resets opportunistically: if daily_reset_at is > 24h old,
-- the UPDATE resets it to now() and sets count = 1 in the same statement.
-- No separate cron or scheduled reset needed.
--
-- Returns zero rows if the pool is empty or every candidate is flagged /
-- at cap. The TypeScript caller interprets that as "fall back to env
-- var VAPI_PHONE_NUMBER_ID".

create or replace function public.pick_vapi_number(
  p_area_code text,
  p_daily_cap int default 75
) returns table (
  id          text,
  twilio_e164 text,
  area_code   text,
  tier        text
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_now timestamptz := now();
begin
  -- Tier 1: area-code match.
  return query
  update public.vapi_phone_numbers p
  set
    last_used_at = v_now,
    daily_call_count = case
      when p.daily_reset_at < v_now - interval '1 day' then 1
      else p.daily_call_count + 1
    end,
    daily_reset_at = case
      when p.daily_reset_at < v_now - interval '1 day' then v_now
      else p.daily_reset_at
    end
  where p.id = (
    select q.id
    from public.vapi_phone_numbers q
    where q.status = 'active'
      and q.area_code = p_area_code
      and (q.daily_reset_at < v_now - interval '1 day' or q.daily_call_count < p_daily_cap)
    order by q.last_used_at nulls first
    limit 1
    for update skip locked
  )
  returning p.id, p.twilio_e164, p.area_code, 'area_code'::text;

  -- plpgsql note: `found` reflects the last `return query` — true if we
  -- returned at least one row above. If we did, stop; caller has a pick.
  if found then
    return;
  end if;

  -- Tier 2: any active.
  return query
  update public.vapi_phone_numbers p
  set
    last_used_at = v_now,
    daily_call_count = case
      when p.daily_reset_at < v_now - interval '1 day' then 1
      else p.daily_call_count + 1
    end,
    daily_reset_at = case
      when p.daily_reset_at < v_now - interval '1 day' then v_now
      else p.daily_reset_at
    end
  where p.id = (
    select q.id
    from public.vapi_phone_numbers q
    where q.status = 'active'
      and (q.daily_reset_at < v_now - interval '1 day' or q.daily_call_count < p_daily_cap)
    order by q.last_used_at nulls first
    limit 1
    for update skip locked
  )
  returning p.id, p.twilio_e164, p.area_code, 'any'::text;

  -- If we reach here with no rows, the pool is empty or exhausted.
  -- Returning zero rows is the signal; caller falls back to env var.
  return;
end;
$$;

-- Service role only. Revoking from anon/authenticated guards against a
-- future RLS-policy misstep that accidentally grants RPC access.
revoke all on function public.pick_vapi_number(text, int) from public;
revoke all on function public.pick_vapi_number(text, int) from anon, authenticated;

comment on function public.pick_vapi_number(text, int) is
  'Atomically claim an active Vapi phone number. Tier-1 prefers area_code match; tier-2 is any active. Bumps daily_call_count + last_used_at.';
